# Generated by Django 4.2 on 2023-05-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='details',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subject',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
